### ISSUE TITLE
配置文件中*, **的区别

### ISSUE THREAD

**Issue by justin201802** [wweir/sower#10]
请问配置文件中*， **是什么意思？有什么区别？
还有，输出的日志文件存放在哪里？

**Comment by justin201802** [comment]
日志文件位置已经找到， /var/log中
*.abc.com   是不是指 匹配  xx.abc.com
**.abc.com  匹配  xx.yy.abc.com

**Comment by wweir** [comment]
是的，理解完全正确。这个用法在其它一些软件中同样存在，所以没做专门的解释。
这一块的实现已经单独实现为后缀匹配树，如果以后单独封包，需要详细介绍。
