### ISSUE TITLE
日志中有大量local ping xxxx fail

### ISSUE THREAD

**Issue by justin201802** [wweir/sower#11]
发现日志中有大量的类似下面的错误信息
`
dns.go:135] local ping events.jianshu.io fail
`
错误的这些域名我在安装sower client的机器上手动ping这些域名， 都是能够正常ping通的。

sower.toml配置文件如下：
```
client_ip = "10.x.x.x"   //安装sower client机器的IP
dns_server = "223.5.5.5"
```

目前的配置，可以正常访问facebook等网站， 但是在suggestion配置项中， 出现了很多本应可以正常访问的网站域名。

**Comment by wweir** [comment]
能 ping 通并不代表没受屏蔽，目前的规则是：
1、http 或 https 访问不了
2、http 和 https 虽然可以访问，但都是走代理比不走代理访问要快

第二种情况可以以一个选配项的方式对外提供，这个是后续版本要加的功能。

如果有什么不符合上述描述的情况，欢迎指出。

**Comment by wweir** [comment]
ping xxx fail 是 verbose 级别日志打出的内容，是屏蔽检测的结果，方便调试使用。
如果嫌烦，可以降低日志的等级

**Comment by justin201802** [comment]
我是特意要看输出的日志的， 因为suggestion中的域名， 是可以正常访问的， 您说的“能ping通，并不代表没受屏蔽”
比如：
```
"apilocate.amap.com",      //高德地图
 "mps.amap.com",
"m.client.10010.com",       //联通官网
  "m1.img.10010.com",
 "adash-c.ut.taobao.com",    //淘宝
  "h-adashx.ut.taobao.com",
等等
```

我觉得这些域名不应该， 也不可能在国内的网络下被屏蔽。

**Comment by wweir** [comment]
@justin201802 日志中有的。为了达到相对较好的 suggest 效果，设计了一套得分规则，每条添加规则的日志都会带上这个域名的得分。2 分被加进去的是加速访问，3、4 分被加进去是因为屏蔽。

**Comment by wweir** [comment]
@justin201802 已添加 `suggest_level` 选项，可按需配置 suggest 强度
```toml
suggest_level="SPEEDUP"          # DISABLE, BLOCK, SPEEDUP
```

**Comment by justin201802** [comment]
感谢， 我更新一下版本再看看日志情况。
