### ISSUE TITLE
是否可以添加arm mips编译输出？

### ISSUE THREAD

**Issue by op69qs** [wweir/sower#12]
比如arm mips的路由设备可以用于更多地方部署

**Comment by wweir** [comment]
可以增加对应预编译文件，但很难直接在家用路由器等设备上直接运行。

sower 的设计里需要占用 udp/53 tcp/80 tcp/443 这三个端口，普通家用路由器上，前两个端口都被预占了，并且是被预占了所有网络 interface 的这两个端口。
预占详情：
- udp/53：dnsmasq
- tcp/80: admin-ui （nginx）

之前考虑过使用 iptables 强行偏转流量的 IP 端口，无奈太不优雅，暂时放弃

**Comment by wweir** [comment]
可以增加对应预编译文件，但很难直接在家用路由器等设备上直接运行。

sower 的设计里需要占用 udp/53 tcp/80 tcp/443 这三个端口，普通家用路由器上，前两个端口都被预占了，并且是被预占了所有网络 interface 的这两个端口。
预占详情：
- udp/53：dnsmasq
- tcp/80: admin-ui （nginx）

之前考虑过使用 iptables 强行偏转流量的 IP 端口，无奈太不优雅，暂时放弃

**Comment by wweir** [comment]
可以增加对应预编译文件，但很难直接在家用路由器等设备上直接运行。

sower 的设计里需要占用 udp/53 tcp/80 tcp/443 这三个端口，普通家用路由器上，前两个端口都被预占了，并且是被预占了所有网络 interface 的这两个端口。
预占详情：
- udp/53：dnsmasq
- tcp/80: admin-ui （nginx）

之前考虑过使用 iptables 强行偏转流量的 IP 端口，无奈太不优雅，暂时放弃

**Comment by wweir** [comment]
Link to #4 
Fix by v0.6.3 f001f7dab7bfabb48a987ee60ed7e94c4c2d456f

**Comment by op69qs** [comment]
got it
