### ISSUE TITLE
服务端怎么做？感觉和客户端匹配不上

### ISSUE THREAD

**Issue by shuish0071** [wweir/sower#15]
大神好：
我的环境是谷歌云有一个虚拟机，做了ssr，想要在本地搭建sower客户端连过去，结果发现
（1）ssr的加密协议和sower的加密协议不兼容，ssr都是aes_128_cfb、aes_256_cfb等
（2）ssr的服务器上安装sower服务端，本地安装sower客户端，结果客户端有加密协议，但是服务端部署的时候没有啊，造成客户端dns能解析出谷歌ip，但是curl www.google.com 失败

请教大神，有什么好的建议吗？

**Comment by shuish0071** [comment]
还有就是如何打开日志？配置文件里没有日志路径，只有一个日志等级

**Comment by wweir** [comment]
1. 可以使用 sower 的 SOCKS5 协议支持，以二级代理的方式接在 ssr 后面
2. 建议翻看 [**配置文档**](https://github.com/wweir/sower/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF-%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%85)
    - 服务端默认安装使用 aes_128_gcm 加密方式，可通过参数修改
    - 需设置客户端机器的 DNS
3. 本人不怎么使用 Windows 设备，测试难免有所疏漏，日志也以最简方式输出。如需变更，可以提交 pr
