### ISSUE TITLE
报错 pick interface: no vaild interface

### ISSUE THREAD

**Issue by leafleave** [wweir/sower#16]
客户端，装在Windows 2008 R2 国内腾讯云上
![image](https://user-images.githubusercontent.com/7804140/60775352-83ad2c80-a154-11e9-890b-08804dd1aafa.png)
配置完后打开就报错，看起来像是找不到网卡，ipconfig如下
![image](https://user-images.githubusercontent.com/7804140/60775377-f3231c00-a154-11e9-9a8a-d8c0c42fd2ea.png)

**Comment by leafleave** [comment]
这是日志文件，不过好像啥也没有

**Comment by wweir** [comment]
腾讯云的机器比较特殊，他们的网络方案是自己做的，看起来是他们的网络环境与正常家用的有所不同，出现了不兼容。
手边没合适的腾讯云 Windows 机器，暂时没法修复了。零时解决方案就是修改 sower.toml，手工设置 `dns_server` 为腾讯云(或者其它你认可的)的 DNS 服务器 IP。
