### ISSUE TITLE
翻不了墙啊

### ISSUE THREAD

**Issue by luckypoem** [wweir/sower#17]
hi。

yudeMacBook-Air:~ brite$ sudo sower -f /usr/local/etc/sower.toml
显示：
...
I0816 22:32:56.906684   31950 client.go:96] listening port: 80
I0816 22:32:56.906773   31950 client.go:96] listening port: 443
I0816 22:32:56.906872   31950 client.go:19] Client started.

我在浏览器上随便访问一个被封的网站，根本就打不开网站。怎么回事？

**Comment by wweir** [comment]
please read the readme file and the wiki.
