### ISSUE TITLE
希望增加自定义DNS监听端口功能，方便做pihole上游

### ISSUE THREAD

**Issue by sjqlwy** [wweir/sower#18]
准备在同一台机器上安装Pi-Hole去广告，安装sower上网，尝试sower监听lan做下级，pi-hole监听127.0.0.1做上级会出问题（可能是我愚笨搞不定），希望能支持自定义dns端口，谢谢

**Comment by wweir** [comment]
已支持自定义上游 dns 端口，设置 dns_server 即可

**Comment by sjqlwy** [comment]
非常感谢您的回复。之前直接改了源代码的端口号，原来直接支持自定义
