### ISSUE TITLE
TCP和QUIC协议无法连接，KCP可以连接

### ISSUE THREAD

**Issue by sjqlwy** [wweir/sower#19]
RT，被识别了嘛
另外更新后的下载脚本地址发生改变，麻烦更新一下，谢谢

**Comment by wweir** [comment]
可能是被识别了，毕竟没做混淆，“境外加密流量”这个最大的特征没有解决。最近手里合适的国外 vps 都被屏蔽了，没法测试。
目前可以考虑使用 sower 接其它代理方案，作为二级代理，只用来解决代理的路由问题。后期准备集成其它成熟代理方案，直接使用成熟方案解决网络传输问题。

ps：脚本地址已更新

**Comment by sjqlwy** [comment]
感谢，工具很方便
