### ISSUE TITLE
一直 dial tcp i/o timeout

### ISSUE THREAD

**Issue by neal1991** [wweir/sower#6]
服务端 5533端口是开通的

**Comment by wweir** [comment]
@neal1991 能给出具体的出错场景吗？curl 报错 i/o timeout?
0.4.0~0.4.1 版本确实有点问题，新增的 DHCP 导致 DNS 工作有些异常，刚推出的 0.4.2 版本已经解决了，不知道你遇到的是否是这个问题。

**Comment by neal1991** [comment]
因为尝试代理未成功 然后在本地查看 sower-client 服务的状态 一直是报这个信息

**Comment by wweir** [comment]
@neal1991 这个需要给出更多信息才能诊断，听描述，初步的判断是与环境有关，如：
- 防火墙配置问题
- 本地机器的 DNS 设置问题

你看到的 i/o timeout 应该是 DNS 规则智能检测过程中遇到的 i/o timeout，可以忽略。
