### ISSUE TITLE
How to use on Windows?

### ISSUE THREAD

**Issue by okeehou** [wweir/sower#8]
I can run this on macOS smoothly without any issue, but when I tried to run it on Windows 10, the sower file has no file extension, and when I run it, it said "sower is not recognized as an internal or external command". 

Then I added the extension "sower.exe" manually, it said "sower.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher." I'm running 64-bit version!

What happened here? How to run it on Windows? 

Look forward to hearing from you soon. Thank you.

**Comment by wweir** [comment]
Please download the correct prebuild file from the [release page](https://github.com/wweir/sower/releases). The correct file name for Windows is `sower_windows_amd64.tar.gz`.

There are some descriptions in the wiki about how to install on your PC.
https://github.com/wweir/sower/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF-%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%85
